#!/bin/bash
# uptime by David Weinman <david@weinman.com>

# collects the time since the last time the uptime was run,
# takes the difference between that time and the current time
# in seconds and runs the uptime perl script which actually
# does the checking and passes that time to it as its only
# argument

lasttime_path=$(echo "/tmp/uptimechecker/lasttime.txt")
current_time="$(date --date="$(date +%Y-%m-%d\ \ %H:%M:%S)" +%s)"

# if the last time run file doesn't exist then make it and dump our new
# time into it
if [ ! -e $lasttime_path ]; then
  makey_time="$(date --date="$(date +%Y-%m-%d\ \ %H:%M:%S)" +%s)"
  last_time="$current_time"
# unless that file happens to be a directory (idk why this would happen either)
# then error and just exit - we still dont want to delete anyone's stuff.
elif [ -d $lasttime_path ]; then
  echo "[*] lasttime.txt is a directory! please remove it - I am exiting now.."
  exit 1;
# else - if the last time file exists then use the contents of that file as
# our prior time instead
elif [ -e $lasttime_path ]; then
  makey_time="$(date --date="$(date +%Y-%m-%d\ \ %H:%M:%S)" +%s)"
  last_time="$(cat $lasttime_path)"
fi

# save our (new) last checked time (this is for the next time it gets run to reference)
echo $makey_time > $lasttime_path

# run our uptime perl script with the difference in times we come up with
/tmp/uptimechecker/uptime.pl $(expr $makey_time - $last_time) 1>> /tmp/uptime.log 2>> /tmp/uptime.log

